### ISSUE TITLE
german fromTo date in same month

### ISSUE THREAD

**Issue by bwbohl** [Edirom/WeGA-WebApp-lib#9]
https://github.com/Edirom/WeGA-WebApp-lib/blob/50683e339aaac8afbdd51cf93d8088b5b77df35c/xquery/date.xqm#L197

unfortunately this does not work in my project… what I get is:

`Vom 1 bis 7. August 1801 `

Missing the full stop after the first day.
I think this is due to:

https://github.com/Edirom/WeGA-WebApp-lib/blob/50683e339aaac8afbdd51cf93d8088b5b77df35c/xquery/date.xqm#L120

which in case of e.g. a date picture string `[D]. [MNn] [Y]` only return `[D]`

Any thoughts?

**Comment by bwbohl** [comment]
probably replacing the regEx in the following line
https://github.com/Edirom/WeGA-WebApp-lib/blob/50683e339aaac8afbdd51cf93d8088b5b77df35c/xquery/date.xqm#L120

with
`.*(\[D[^\]]*\][^ ]).*`

could fix it.

**Comment by peterstadler** [comment]
First, thanks for the heads up! 
I revisited that function and fixed some laziness in the code: The callback function `$get-language-string` now expects three parameters (which I silently supplied in the calling function before). NB: This breaks backwards compatibility but should be easy to fix …

Your original issue is IMHO best solved if you change your picture string to "[D1o] [MNn] [Y]". I know that "[D]. [MNn] [Y]" is not uncommon but I hesitate to pull in your change because it introduces other issues: a) your regex now enforces a trailing character and b) what about picture strings that do not separate by whitespace like e.g. "[M]/[D]/[Y]"?

**Comment by bwbohl** [comment]
Thanks, your proposed date picture string works like a charm ;-)
Of course #10 can be considered closed then as can this ticket!
